# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip', models.IntegerField()),
                ('bedrooms', models.IntegerField(choices=[(1, '1 bedroom'), (2, '2 bedrooms'), (3, '3 bedrooms'), (4, '4 bedrooms'), (5, '5 bedrooms'), (6, '6 bedrooms'), (7, '7 bedrooms'), (8, '8 bedrooms'), (9, '9 bedrooms'), (10, '10 bedrooms')])),
                ('bathrooms', models.IntegerField(choices=[(1, '1 bathroom'), (2, '2 bathrooms'), (3, '3 bathrooms'), (4, '4 bathrooms'), (5, '5 bathrooms'), (6, '6 bathrooms'), (7, '7 bathrooms'), (8, '8 bathrooms'), (9, '9 bathrooms'), (10, '10 bathrooms')])),
                ('hours', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
