# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='hours',
            field=models.IntegerField(choices=[(1, '1 hour'), (1.5, ' 1.5 hours'), (2, '2 hours'), (2.5, ' 2.5 hours'), (3, '3 hours'), (3.5, ' 3.5 hours'), (4, '4 hours'), (4.5, ' 4.5 hours'), (5, '5 hours'), (5.5, ' 5.5 hours'), (6, '6 hours'), (6.5, ' 6.5 hours'), (7, '7 hours'), (7.5, ' 7.5 hours'), (8, '8 hours'), (8.5, ' 8.5 hours'), (9, '9 hours'), (9.5, ' 9.5 hours'), (10, '10 hours')]),
        ),
    ]
